name: feature-pipeline
on:
  push:
    branches:
      - 'feature-*'
  workflow_dispatch:

jobs:
  feature-pipeline:
    if: github.ref_name != 'main'
    permissions:
      statuses: write
    uses: 88s-org/workflows/.github/workflows/nodejs-feature-pipeline.yaml@main
    with:
      project: 'roboshop'
      component: 'catalogue'

    secrets: inherit

